ci:
- changed-files:
    - any-glob-to-any-file: ['.github/workflows/*']

backend:
- changed-files:
    - any-glob-to-any-file: ['WeatherPlannerAPI/*']

docs:
- changed-files:
    - any-glob-to-any-file: ['README.md']
